[versions]
springBoot = "3.5.4"
graalvm = "0.11.0"
springDependencyManagement = "1.1.7"

[libraries]
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-devtools = { module = "org.springframework.boot:spring-boot-devtools" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }

[plugins]
graalvm-buildtools-native = { id = "org.graalvm.buildtools.native", version.ref = "graalvm"}
springframework-boot = { id = "org.springframework.boot", version.ref = "springBoot"}
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "springDependencyManagement" }
